### ISSUE TITLE
Module does not compile on arm64

### ISSUE THREAD

**Issue by rodmaz** [awslabs/aws-crt-nodejs#170]
Decided to deploy this node package in a clean Ubuntu 20 LTS (arm64) distribution running on Raspberry Pi 3B. Results are no good. 🥺

We are using:

- Node 12.18.2
- npm 6.14.8
- cmake 3.16.3.

The package does install successfully but module linking fails.

```
> aws-crt@1.3.8 install /home/ubuntu/cross-compiling/node_modules/aws-crt
> node ./scripts/install.js

info TOOL Using Unix Makefiles generator.
info TOOL Building only the install target, as specified from the command line.
info CMD CONFIGURE
info TOOL Building only the install target, as specified from the command line.
info RUN cmake "/home/ubuntu/cross-compiling/node_modules/aws-crt" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_JS_VERSION="6.1.0" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/ubuntu/cross-compiling/node_modules/aws-crt/build/Release" -DCMAKE_JS_INC="/home/ubuntu/.cmake-js/node-arm64/v12.18.2/include/node" -DCMAKE_JS_SRC="" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="12.18.2" -DNODE_ARCH="arm64" -DCMAKE_EXPORT_COMPILE_COMMANDS="true" -DCMAKE_JS_PLATFORM="linux" -DCMAKE_JS_ARCH="arm64" -DBUILD_TESTING="OFF"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 10.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Using submodule dependencies
-- CMake 3.16.3
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Failed
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Success
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Success
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Failed
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Failed
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAS_MOUTLINE_ATOMICS
-- Performing Test HAS_MOUTLINE_ATOMICS - Success
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Packaging currently only supported on Fedora.
-- Found LibCrypto: /usr/lib/aarch64-linux-gnu/libcrypto.a  
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/aarch64-linux-gnu/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/aarch64-linux-gnu/libcrypto.a
-- Attempting to try_compile PQ ASM
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- PQ ASM try_compile failed - using generic C code for PQ crypto
-- Performing Test S2N_HAVE_EXECINFO
-- Performing Test S2N_HAVE_EXECINFO - Success
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/aarch64-linux-gnu/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/aarch64-linux-gnu/libcrypto.a
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/aarch64-linux-gnu/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/aarch64-linux-gnu/libcrypto.a
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/aarch64-linux-gnu/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/aarch64-linux-gnu/libcrypto.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/cross-compiling/node_modules/aws-crt/build
```

Towards the very end, the linking step fails:

```
gmake[2]: Leaving directory '/home/ubuntu/cross-compiling/node_modules/aws-crt/build'
[ 94%] Built target aws-c-auth
gmake[2]: Entering directory '/home/ubuntu/cross-compiling/node_modules/aws-crt/build'
Scanning dependencies of target aws-crt-nodejs
gmake[2]: Leaving directory '/home/ubuntu/cross-compiling/node_modules/aws-crt/build'
gmake[2]: Entering directory '/home/ubuntu/cross-compiling/node_modules/aws-crt/build'
[ 94%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/auth.c.o
[ 95%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/class_binder.c.o
[ 95%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/crypto.c.o
[ 95%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/http_connection.c.o
[ 96%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/http_connection_manager.c.o
[ 96%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/http_headers.c.o
[ 96%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/http_message.c.o
[ 96%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/http_stream.c.o
[ 97%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/io.c.o
[ 97%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/logger.c.o
[ 97%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/module.c.o
[ 98%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/mqtt_client.c.o
[ 98%] Building C object CMakeFiles/aws-crt-nodejs.dir/source/mqtt_client_connection.c.o
[ 98%] Linking C shared library Release/aws-crt-nodejs.node
/usr/bin/ld: /usr/lib/aarch64-linux-gnu/libcrypto.a(sha1-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/lib/aarch64-linux-gnu/libcrypto.a(sha1-armv8.o): in function `sha1_block_armv8':
(.text+0x1240): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/aarch64-linux-gnu/libcrypto.a(chacha-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/lib/aarch64-linux-gnu/libcrypto.a(chacha-armv8.o):(.text+0x20): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o): relocation R_AARCH64_ADR_PREL_LO21 against symbol `poly1305_blocks' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o): in function `poly1305_init':
(.text+0x40): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o): relocation R_AARCH64_ADR_PREL_LO21 against symbol `poly1305_emit' which may bind externally can not be used when making a shared object; recompile with -fPIC
(.text+0x48): dangerous relocation: unsupported relocation
/usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o): in function `poly1305_blocks_neon':
(.text+0x26c): relocation truncated to fit: R_AARCH64_CONDBR19 against symbol `poly1305_blocks' defined in .text section in /usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o)
/usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o): in function `poly1305_emit_neon':
(.text+0x904): relocation truncated to fit: R_AARCH64_CONDBR19 against symbol `poly1305_emit' defined in .text section in /usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o)
/usr/bin/ld: /usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
(.text+0x9a0): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/aarch64-linux-gnu/libcrypto.a(sha256-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/lib/aarch64-linux-gnu/libcrypto.a(sha256-armv8.o): in function `sha256_block_data_order':
(.text+0xf88): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/lib/aarch64-linux-gnu/libcrypto.a(sha512-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/lib/aarch64-linux-gnu/libcrypto.a(sha512-armv8.o): in function `sha512_block_data_order':
(.text+0x1108): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/aws-crt-nodejs.dir/build.make:274: Release/aws-crt-nodejs.node] Error 1
gmake[2]: Leaving directory '/home/ubuntu/cross-compiling/node_modules/aws-crt/build'
gmake[1]: *** [CMakeFiles/Makefile2:290: CMakeFiles/aws-crt-nodejs.dir/all] Error 2
gmake[1]: Leaving directory '/home/ubuntu/cross-compiling/node_modules/aws-crt/build'
gmake: *** [Makefile:130: all] Error 2
ERR! OMG Process terminated: 2
(node:39593) UnhandledPromiseRejectionWarning: Error: Process terminated: 2
    at ChildProcess.<anonymous> (/home/ubuntu/cross-compiling/node_modules/cmake-js/lib/processHelpers.js:29:32)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
(node:39593) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:39593) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is this module not supported in ARM64?

**Comment by rodmaz** [comment]
Figured out the reason. The problem is due to an issue on OpenSSL libs (1.1.1f), which is by default installed on Ubuntu 20 LTS.
See https://github.com/openssl/openssl/issues/10842

In order to fix this, replace the OpenSSL by its newer version (1.1.1i) and rebuild the module.
