### ISSUE TITLE
MSBUILD : error MSB1009: Project file does not exist.

### ISSUE THREAD

**Issue by zhex900** [awslabs/aws-crt-nodejs#222]
Hi,

I trying to rebuild aws-crt on windows 10. 

But I get this error. 

What should I do?

````
PS C:\Code\aws-crt-nodejs> npm run prepare

> aws-crt@1.0.0-dev prepare C:\Code\aws-crt-nodejs
> node ./scripts/tsc.js && node ./scripts/build.js

> npx tsc -p tsconfig.json
> npx tsc -p tsconfig.browser.json
info TOOL Using Visual Studio 15 2017 Win64 generator.
info CMD BUILD
info RUN cmake --build "C:\Code\aws-crt-nodejs\build" --config Release --target install
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: install.vcxproj
ERR! OMG Process terminated: 1
(node:832) UnhandledPromiseRejectionWarning: Error: Process terminated: 1
    at ChildProcess.<anonymous> (C:\Code\aws-crt-nodejs\node_modules\cmake-js\lib\processHelpers.js:29:32)
    at ChildProcess.emit (events.js:376:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by TingDaoK** [comment]
Hey, 

Can you check if you pulled all the submodules by checking the crt/aws-c-common folder is empty or not?
If it's empty, please run the following command `git submodule update --init --recursive` to pull all of the submodules and try again.

**Comment by zhex900** [comment]
```
PS C:\Code\aws-crt-nodejs> ls crt


    Directory: C:\Code\aws-crt-nodejs\crt


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         6/16/2021   9:10 AM                aws-c-auth
d-----         6/16/2021   9:10 AM                aws-c-cal
d-----         6/16/2021   9:10 AM                aws-c-common
d-----         6/16/2021   9:10 AM                aws-c-compression
d-----         6/16/2021   9:10 AM                aws-c-http
d-----         6/16/2021   9:10 AM                aws-c-io
d-----         6/16/2021   9:10 AM                aws-c-mqtt
d-----         6/16/2021   9:10 AM                aws-lc
d-----         6/16/2021   9:11 AM                s2n

````

`crt` is not empty. I did `git submodule update --init --recursive` anyway. 

`npm run prepare` gave the same errors. 

I tried to build it using `aws-crt-builder` but the test failed. 

https://github.com/awslabs/aws-crt-builder/issues/127

**Comment by TingDaoK** [comment]
remove the build/ and try again

**Comment by TingDaoK** [comment]
So, cmake-js will have different building cmd if it's not a clean rebuild, the previous configuration without submodules will still be used. Need to remove ./build/ folder

**Comment by TingDaoK** [comment]
https://github.com/awslabs/aws-crt-nodejs/pull/224 Added the instruction about building from source, we missed the submodule instruction there. Sorry about it.

**Comment by zhex900** [comment]
`del build` and rerun `npm run prepare` fixed it. Thank you!
