### ISSUE TITLE
Installation on raspbian fails

### ISSUE THREAD

**Issue by mangelino** [awslabs/aws-crt-nodejs#97]
`npm i aws-crt`

results in:
```
> aws-crt@1.1.5 install /home/pi/node_modules/aws-crt
> node ./scripts/install.js

module.js:550
    throw err;
    ^

Error: Cannot find module 'cmake-js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/node_modules/aws-crt/scripts/build.js:17:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

Installed CMake via
`apt install cmake`

installed cmake-js via 
`npm i cmake-js`

Run again `npm i aws-crt`

This time fails:

```
> aws-crt@1.1.5 install /home/pi/aws-crt/node_modules/aws-crt
> node ./scripts/install.js

info TOOL Using Unix Makefiles generator.
info TOOL Building only the install target, as specified from the command line.
info DIST Downloading distribution files.
http DIST 	- https://nodejs.org/dist/v8.17.0/SHASUMS256.txt
http DIST 	- https://nodejs.org/dist/v8.17.0/node-v8.17.0-headers.tar.gz
info CMD CONFIGURE
info TOOL Building only the install target, as specified from the command line.
info RUN cmake "/home/pi/aws-crt/node_modules/aws-crt" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_JS_VERSION="6.1.0" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/pi/aws-crt/node_modules/aws-crt/build/Release" -DCMAKE_JS_INC="/home/pi/.cmake-js/node-arm/v8.17.0/include/node" -DCMAKE_JS_SRC="" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="8.17.0" -DNODE_ARCH="arm" -DCMAKE_EXPORT_COMPILE_COMMANDS="true" -DCMAKE_JS_PLATFORM="linux" -DCMAKE_JS_ARCH="arm"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Using submodule dependencies
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Failed
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Failed
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Packaging currently only supported on Fedora.
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibCrypto (missing: LibCrypto_LIBRARY LibCrypto_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  aws-common-runtime/s2n/cmake/modules/FindLibCrypto.cmake:61 (find_package_handle_standard_args)
  CMakeLists.txt:40 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/pi/aws-crt/node_modules/aws-crt/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/aws-crt/node_modules/aws-crt/build/CMakeFiles/CMakeError.log".
ERR! OMG Process terminated: 1
(node:6585) UnhandledPromiseRejectionWarning: Error: Process terminated: 1
    at ChildProcess.<anonymous> (/home/pi/aws-crt/node_modules/cmake-js/lib/processHelpers.js:29:32)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
(node:6585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6585) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Find out that LibCrypto is part of libel-dev. Install via `sudo apt install libssl-dev`

Run again `npm i aws-crt`, which fails with the same error as in  issue #80:

```

> aws-crt@1.1.5 install /home/pi/aws-crt/node_modules/aws-crt
> node ./scripts/install.js

info TOOL Using Unix Makefiles generator.
info TOOL Building only the install target, as specified from the command line.
info CMD CONFIGURE
info TOOL Building only the install target, as specified from the command line.
info RUN cmake "/home/pi/aws-crt/node_modules/aws-crt" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_JS_VERSION="6.1.0" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/pi/aws-crt/node_modules/aws-crt/build/Release" -DCMAKE_JS_INC="/home/pi/.cmake-js/node-arm/v8.17.0/include/node" -DCMAKE_JS_SRC="" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="8.17.0" -DNODE_ARCH="arm" -DCMAKE_EXPORT_COMPILE_COMMANDS="true" -DCMAKE_JS_PLATFORM="linux" -DCMAKE_JS_ARCH="arm"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Using submodule dependencies
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Failed
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Failed
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Packaging currently only supported on Fedora.
-- Found LibCrypto: /usr/lib/arm-linux-gnueabihf/libcrypto.a
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/arm-linux-gnueabihf/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/arm-linux-gnueabihf/libcrypto.a
-- Attempting to try_compile PQ ASM
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
CMake Error at /home/pi/aws-crt/node_modules/aws-crt/build/CMakeFiles/CMakeTmp/CMakeLists.txt:15 (add_executable):
  Cannot find source file:

    /home/pi/aws-crt/node_modules/aws-crt/aws-common-runtime/s2n/tests/unit/s2n_pq_asm_noop_test.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at /home/pi/aws-crt/node_modules/aws-crt/build/CMakeFiles/CMakeTmp/CMakeLists.txt:15 (add_executable):
  No SOURCES given to target: cmTC_68eeb


CMake Error at aws-common-runtime/s2n/CMakeLists.txt:118 (try_compile):
  Failed to generate test project build system.


-- Configuring incomplete, errors occurred!
See also "/home/pi/aws-crt/node_modules/aws-crt/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/aws-crt/node_modules/aws-crt/build/CMakeFiles/CMakeError.log".
ERR! OMG Process terminated: 1
(node:7097) UnhandledPromiseRejectionWarning: Error: Process terminated: 1
    at ChildProcess.<anonymous> (/home/pi/aws-crt/node_modules/cmake-js/lib/processHelpers.js:29:32)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
(node:7097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7097) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by carmenates09** [comment]
We have the same issue on `Raspbian GNU/Linux 9 (stretch)` with `NodeJS`

$npm i aws-crt
```
> aws-crt@1.1.5 install /home/pi/station-backend/node_modules/aws-crt
> node ./scripts/install.js
info TOOL Using Unix Makefiles generator.
info TOOL Building only the install target, as specified from the command line.
info CMD CONFIGURE
info TOOL Building only the install target, as specified from the command line.
info RUN cmake "/home/pi/station-backend/node_modules/aws-crt" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_JS_VERSION="6.1.0" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/pi/station-backend/node_modules/aws-crt/build/Release" -DCMAKE_JS_INC="/home/pi/.cmake-js/node-arm/v12.13.1/include/node" -DCMAKE_JS_SRC="" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="12.13.1" -DNODE_ARCH="arm" -DCMAKE_EXPORT_COMPILE_COMMANDS="true" -DCMAKE_JS_PLATFORM="linux" -DCMAKE_JS_ARCH="arm"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Using submodule dependencies
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Failed
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Failed
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Packaging currently only supported on Fedora.
-- Found LibCrypto: /usr/lib/arm-linux-gnueabihf/libcrypto.a  
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/arm-linux-gnueabihf/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/arm-linux-gnueabihf/libcrypto.a
-- Attempting to try_compile PQ ASM
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
CMake Error at /home/pi/station-backend/node_modules/aws-crt/build/CMakeFiles/CMakeTmp/CMakeLists.txt:15 (add_executable):
  Cannot find source file:
    /home/pi/station-backend/node_modules/aws-crt/aws-common-runtime/s2n/tests/unit/s2n_pq_asm_noop_test.c
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error: CMake can not determine linker language for target: cmTC_6fa2d
CMake Error: Cannot determine link language for target "cmTC_6fa2d".
CMake Error: Internal CMake error, TryCompile generation of cmake failed
-- PQ ASM try_compile failed - using generic C code for PQ crypto
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/arm-linux-gnueabihf/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/arm-linux-gnueabihf/libcrypto.a
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/arm-linux-gnueabihf/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/arm-linux-gnueabihf/libcrypto.a
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/arm-linux-gnueabihf/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/arm-linux-gnueabihf/libcrypto.a
-- Configuring incomplete, errors occurred!
See also "/home/pi/station-backend/node_modules/aws-crt/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/station-backend/node_modules/aws-crt/build/CMakeFiles/CMakeError.log".
ERR! OMG Process terminated: 1
(node:19423) UnhandledPromiseRejectionWarning: Error: Process terminated: 1
    at ChildProcess.<anonymous> (/home/pi/station-backend/node_modules/cmake-js/lib/processHelpers.js:29:32)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:19423) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19423) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN bln-station-backend@1.0.0 No repository field.
+ aws-crt@1.1.5
updated 1 package and audited 752 packages in 52.399s
18 packages are looking for funding
  run `npm fund` for details
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by bretambrose** [comment]
Hello,

It looks like everybody is stuck on the same problem.  I know it sounds like a dumb question, but to start off, does that file actually exist on your device (/home/pi/station-backend/node_modules/aws-crt/aws-common-runtime/s2n/tests/unit/s2n_pq_asm_noop_test.c)?

**Comment by jeffxor** [comment]
@bretambrose 

I am having the same issue.

I can confirm that the file `aws-crt/aws-common-runtime/s2n/tests/unit/s2n_pq_asm_noop_test.c` does not exist. Looking at the folder structure their are no test provides in the installed package contents.

**Comment by jeffxor** [comment]
@carmenates09 any updates from you with this issue? 

I don't see how I can move forward with using JS with AWS IoT on Raspberry PI without a build/binary for it. The older version of `aws-iot-device-sdk` is no longer support and `aws-iot-device-sdk-v2` depends on aws-crt.

The only option appears to be to use a different language?

**Comment by bretambrose** [comment]
I have ordered a pi and it should arrive tomorrow.  I will try and make some progress on this once I have it up and running.

**Comment by jeffxor** [comment]
No need for the PI it can be replicated in Docker.

Attached is a Dockerfile that allows build of the 1.0.4. Anything later than that fails.

[Dockerfile.txt](https://github.com/awslabs/aws-crt-nodejs/files/4928505/Dockerfile.txt)

**Comment by bretambrose** [comment]
v1.2.3 of the v2 sdk has just been released and the source installation related error (s2n test file) should be fixed.
